services:
  postgres:
    image: postgres:14
    container_name: greenroots-postgres
    environment:
      POSTGRES_USER: greenroots
      POSTGRES_PASSWORD: greenroots
      POSTGRES_DB: greenroots
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: greenroots-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres

volumes:
  postgres_data: